sudo: required
language: php
services:
- docker
script:
- docker build -t phpimage .
post_install:
- docker tag phpimage brouly10/phpimage
- docker push brouly10/phpimage
before_deploy:
- curl -fSL "https://releases.hashicorp.com/terraform/0.11.5/terraform_0.11.5_linux_amd64.zip"
  -o terraform.zip
- sudo unzip terraform.zip -d /opt/terraform
- sudo ln -s /opt/terraform/terraform /usr/bin/terraform
- rm -f terraform.zip
- aws configure
deploy:
- provider: script
  skip_cleanup: true
  script: ./deploy.sh
env:
  global:
  - secure: b7LnvGqoxFw9D/UUx6mkjGplqOoriYV1Wjp1Ppntyp3tKLhNSZZ3QV9EeHqaBprfceD4BQVJbB5azKMnFQCyZrS0o9YUWorBJ+5soKhjiKUJVWLPFQ7V5M7jfCThEtev2+OEFnRqFxlLgBYVewTxVuRaFdNEazcYiZH2969YOJAaw0RH7SMyuJAA9BEVdTE/ap7LxMZXDovg2plp+JOJJqegTIbVzZoDOiCVE1tpRw+gQ5eDMaEQu6fB1lYPPWRS6YrrrAtZth2ZoOQBTUowvC+4jpDQh9hgub59ofosRIv1KsjtMKn3wfOhTo6JtZLWcrRZXCM7UVXeR2cqidDJKv1IStDKCpZjL3S66wV5k5XNk1+w8mFkhJoNkQ7PYngA49BotgpUsXogecowMtloT9DBL8NbSxJwBHbMZzUIyIsD+If/dg2FxAJrUlwncwUea1L5F7+AAu48wpxusJ6oeYoclSh4rAn+80fPLk48o/npGBWLGKj+4nLLWt96Fz0ODg7HUgtrauLA9MQ8o/tVW/LH0krlPyp6/XljKGYib/6hLQHg6Ge7P0w57Xop+Dj4ESOX80I4fQjitdxpkh5aKuecrH3UhKJjbhj6e5WlbR0qOWuGyGVZedlK7RTwLLU0zU/hfnNsfsk5+VMRDn0D2pxWepayYTGe+r4ap6oT7Zc=
  - secure: IcZzvyvbZy0xk6gZuteQHu7JIevWT478QAHJVkVV5TVP7Q4mYDqTrak3VdSkfEcSG/wsr25zPY89GJWrjxK6BPM9BoO9LQ8K5nHAX8vprjF6b/yimaUtK4yzGzJ+sxGhg0KB24YrdlAcBqrt1xGYGoXhNT2om0RZrrTxGdifO95a9qEmcrbdQIDcCr7gZ75+UXGygnZMhtkTd071JyoDjpCjdRjdvQsQZIZm48pZqaKuhaitJWckK/FzN86uQIxfYLfNy07z5KynqGLbXfthYwDbsUmdANbnsgG03j9FQaUjvzPPz6+WyBhVGu2RUDTD20b0VCho7CHHBWnUTBHVjoKj17V1E2ZRcwakCUgZwV+zPeeiHlFX93V1QE3Ym3GyvcArMo+X0qKi0lpqx1+mBQkbiZUm0wsdygQaJ3jjShrtdksrIucCTCrhL1AHMD5UJVa6et4Pibzir2JJ+cWGEcW0WK3X48/MXDNx3NIS5ikpJljPnz1sBVFT2P4WOP99pXN2ny+DiqzvGusfjZrrPt1/pT1B3cfwt4T+NuNmLK98pBEDezpqHruekK+ABuQw8rYs8GtUDjKikM9wNAbNqsQDQwhsMixzheaWEx78QpZhc2X2ZAaVs8DgiCUmHJETRPg5ehSWznLPx2vvCp5cTBZlw4SbHs4qPbTrpN5AJms=
