# travis.yml
sudo: required

language: php

services:
   - docker
   
script:
  # Build docker image
 - docker build -t phpimage .

post_install:
  # Push docker image to Docker Hub
 - docker tag phpimage brouly10/phpimage
 - docker push brouly10/phpimage

before_deploy:
   # Install terraform
  - curl -fSL "https://releases.hashicorp.com/terraform/0.6.15/terraform_0.6.15_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
deploy:
   # Deploy using terraform
  - cd terraform
  - terraform plan
  - terraform apply
